"""Small fixed raw dataset for the agent demo."""

from __future__ import annotations

RAW_DATASETS = {
    "demo_orders_q2": [
        {
            "order_id": "A1001",
            "date": "2026-04-03",
            "customer": "Northwind Studio",
            "segment": "SMB",
            "region": "Taiwan",
            "channel": "web",
            "sku": "starter-kit",
            "quantity": "3",
            "unit_price": "1200",
            "discount_pct": "0.05",
            "status": "paid",
        },
        {
            "order_id": "A1002",
            "date": "2026-04-07",
            "customer": "Fabrikam Labs",
            "segment": "Enterprise",
            "region": "Japan",
            "channel": "sales",
            "sku": "pro-license",
            "quantity": "10",
            "unit_price": "3800",
            "discount_pct": "0.15",
            "status": "paid",
        },
        {
            "order_id": "A1003",
            "date": "2026-04-11",
            "customer": "Blue Pine",
            "segment": "SMB",
            "region": "Taiwan",
            "channel": "partner",
            "sku": "starter-kit",
            "quantity": "2",
            "unit_price": "1200",
            "discount_pct": "",
            "status": "paid",
        },
        {
            "order_id": "A1004",
            "date": "2026-05-02",
            "customer": "Northwind Studio",
            "segment": "SMB",
            "region": "Taiwan",
            "channel": "web",
            "sku": "support-pack",
            "quantity": "1",
            "unit_price": "800",
            "discount_pct": "0",
            "status": "refunded",
        },
        {
            "order_id": "A1005",
            "date": "2026-05-08",
            "customer": "Contoso Health",
            "segment": "Enterprise",
            "region": "Singapore",
            "channel": "sales",
            "sku": "pro-license",
            "quantity": "6",
            "unit_price": "3800",
            "discount_pct": "0.35",
            "status": "paid",
        },
        {
            "order_id": "A1006",
            "date": "2026-05-15",
            "customer": "Litware Retail",
            "segment": "Mid-Market",
            "region": "Korea",
            "channel": "web",
            "sku": "analytics-addon",
            "quantity": "4",
            "unit_price": "2100",
            "discount_pct": "0.1",
            "status": "paid",
        },
        {
            "order_id": "A1007",
            "date": "2026-05-27",
            "customer": "Blue Pine",
            "segment": "SMB",
            "region": "Taiwan",
            "channel": "partner",
            "sku": "analytics-addon",
            "quantity": "1",
            "unit_price": "2100",
            "discount_pct": "0.75",
            "status": "paid",
        },
        {
            "order_id": "A1008",
            "date": "2026-06-04",
            "customer": "Fabrikam Labs",
            "segment": "Enterprise",
            "region": "Japan",
            "channel": "sales",
            "sku": "support-pack",
            "quantity": "3",
            "unit_price": "800",
            "discount_pct": "0",
            "status": "paid",
        },
        {
            "order_id": "A1009",
            "date": "2026-06-12",
            "customer": "Contoso Health",
            "segment": "Enterprise",
            "region": "Singapore",
            "channel": "sales",
            "sku": "analytics-addon",
            "quantity": "-1",
            "unit_price": "2100",
            "discount_pct": "0",
            "status": "paid",
        },
        {
            "order_id": "A1010",
            "date": "2026-06-19",
            "customer": "Litware Retail",
            "segment": "Mid-Market",
            "region": "",
            "channel": "web",
            "sku": "starter-kit",
            "quantity": "5",
            "unit_price": "1200",
            "discount_pct": "0.08",
            "status": "paid",
        },
    ]
}

DEFAULT_INSTRUCTION = (
    "請根據 demo_orders_q2 raw data，整理 Q2 營收摘要、找出異常或需要跟進的客戶，"
    "最後請驗證你要輸出的關鍵數字是否和工具計算結果一致。"
)

